acceso/urls.py
from django.urls import path
from .views import LoginView, login, logout

app_name = 'acceso'

urlpatterns = [
    path('', LoginView.as_view(), name='acceso' ),
    path('login/', login, name='login' ),
    path('logout/', logout, name='logout' ),
]

core/urls.py
from django.urls import path

from core.views.directores import DirectorDetailView, DirectorView
from core.views.actores import ActoresView, ActoresDetailView
from core.views.peliculas import PeliculasView, PeliculasDetailView
from .views.index import index

urlpatterns = [
    path('', index, name="index"),

    path('directores/', DirectorView.as_view(), name='directores' ),
    path('directores/<int:id>/', DirectorDetailView.as_view(), name='directores_editar' ),

    path('actores/', ActoresView.as_view(), name='actores' ),
    path('actores/<int:id>/', ActoresDetailView.as_view(), name='actores_editar' ),

    path('peliculas/', PeliculasView.as_view(), name='peliculas' ),
    path('peliculas/<int:id>/', PeliculasDetailView.as_view(), name='peliculas_editar' ),
]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido

urlpatterns = [
    path('',  decorator_include(login_requerido,include('core.urls'))),
    path('acceso/', include('acceso.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.


class Director(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.age})"


class Pelicula(models.Model):

    CLASIFICACION_CHOICES = (
        ('F', 'MENOR DE EDAD'),
        ('A', 'MAYOR DE EDAD'),
    )

    GENERO_CHOISES  = (
        ('A', 'Accion'),
        ('D', 'Drama'),
        ('C', 'Comedia'),
        ('S', 'Suspenso'),
        ('T', 'Terror'),
        ('O', 'Otro'),
    )

    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_de_estreno = models.DateField()
    duracion = models.IntegerField()
    calificacion = models.IntegerField()
    genero = models.CharField(max_length=1, choices=GENERO_CHOISES, default='A')
    clasificacion = models.CharField(max_length=1, choices=CLASIFICACION_CHOICES, default='F')
    director = models.ForeignKey(Director,related_name='peliculas', on_delete=models.CASCADE)
    estado = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.titulo

class Actor(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    peliculas = models.ManyToManyField(Pelicula, related_name='actores')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

core/forms.py
from django import forms

from core.models import Actor, Director, Pelicula

class PeliculaForm(forms.ModelForm):

    class Meta:
        model = Pelicula
        fields = ['titulo', 'descripcion', 'fecha_de_estreno', 'duracion', 'genero','calificacion', 'clasificacion', 'director', 'estado']

        labels = {
            'titulo': 'Titulo',
            'descripcion': 'Descripcion',
            'fecha_de_estreno': 'Fecha de estreno',
            'duracion': 'Duracion',
            'genero': 'Genero',
            'calificacion': 'Calificacion',
            'clasificacion': 'Clasificacion',
            'director': 'Director',
            'estado': 'Estado',
        }

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'fecha_de_estreno': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}, format='%Y-%m-%d'),
            'duracion': forms.NumberInput(attrs={'class': 'form-control'}),
            'genero': forms.Select(attrs={'class': 'form-select'}),
            'calificacion': forms.NumberInput(attrs={'class': 'form-control'}),
            'clasificacion': forms.Select(attrs={'class': 'form-select'}),
            'director': forms.Select(attrs={'class': 'form-select'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = ['name', 'age', 'peliculas']

        labels = {
            'name': 'Nombre',
            'age': 'Edad',
            'peliculas': 'Peliculas',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'peliculas': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }

class DirectorForm(forms.ModelForm):
    class Meta:
        model = Director
        fields = ['name', 'age']

        labels = {
            'name': 'Nombre',
            'age': 'Edad',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
        }

core/views/actores.py
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from core.models import Actor
from core.forms import ActorForm

class ActoresView(View):
    
    def get(self, request):
        contexto = {
            'form': ActorForm(), 
            'actores' : Actor.objects.all(),
        }
        return render(request, 'core/actores.html', contexto)

    def post(self, request):
        print(request.POST)
        form = ActorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'actores Creado')
            return redirect(reverse('actores'))
        else:
            contexto = {
                'form': form, 
                'actores' : Actor.objects.all(),
            }
            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/actores.html', contexto) 

class ActoresDetailView(View):
    
    def get(self, request, id):
        Actores = Actor.objects.get(id=id)
        contexto = {
            'form': ActorForm(instance=Actores), 
            'actores' : Actor.objects.all(),
        }
        return render(request, 'core/actores.html', contexto)

    def post(self, request, id):
        
        Actores = Actor.objects.get(id=id)

        form = ActorForm(request.POST, instance=Actores)
        if form.is_valid():
            form.save()
            messages.success(request, 'actores Editado')
            return redirect(reverse('actores'))
        else:

            contexto = {
                'form': form, 
                'Actoreses' : Actor.objects.all(),
            }

            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/actores.html', contexto) 

core/views/directores.py
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from core.models import Director
from core.forms import DirectorForm

class DirectorView(View):
    
    def get(self, request):
        contexto = {
            'form': DirectorForm(), 
            'directores' : Director.objects.all(),
        }
        return render(request, 'core/directores.html', contexto)

    def post(self, request):
        print(request.POST)
        form = DirectorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Director Creado')
            return redirect(reverse('directores'))
        else:
            contexto = {
                'form': form, 
                'directores' : Director.objects.all(),
            }
            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/directores.html', contexto) 

class DirectorDetailView(View):
    
    def get(self, request, id):
        director = Director.objects.get(id=id)
        contexto = {
            'form': DirectorForm(instance=director), 
            'directores' : Director.objects.all(),
        }
        return render(request, 'core/directores.html', contexto)

    def post(self, request, id):
        
        director = Director.objects.get(id=id)

        form = DirectorForm(request.POST, instance=director)
        if form.is_valid():
            form.save()
            messages.success(request, 'Director Editado')
            return redirect(reverse('directores'))
        else:

            contexto = {
                'form': form, 
                'directores' : Director.objects.all(),
            }

            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/directores.html', contexto) 

core/views/index.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

core/views/peliculas.py
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from core.models import Pelicula
from core.forms import PeliculaForm

class PeliculasView(View):
    
    def get(self, request):
        contexto = {
            'form': PeliculaForm(), 
            'peliculas' : Pelicula.objects.all(),
        }
        return render(request, 'core/peliculas.html', contexto)

    def post(self, request):
        print(request.POST)
        form = PeliculaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pelicula Creado')
            return redirect(reverse('peliculas'))
        else:
            contexto = {
                'form': form, 
                'peliculas' : Pelicula.objects.all(),
            }
            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/peliculas.html', contexto) 

class PeliculasDetailView(View):
    
    def get(self, request, id):
        director = Pelicula.objects.get(id=id)
        contexto = {
            'form': PeliculaForm(instance=director), 
            'peliculas' : Pelicula.objects.all(),
        }
        return render(request, 'core/peliculas.html', contexto)

    def post(self, request, id):
        
        director = Pelicula.objects.get(id=id)

        form = PeliculaForm(request.POST, instance=director)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pelicula Editado')
            return redirect(reverse('peliculas'))
        else:

            contexto = {
                'form': form, 
                'peliculas' : Pelicula.objects.all(),
            }

            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/peliculas.html', contexto) 

core/templates/core/actores.html
{% extends "core/base.html"%}

{% block titulo %}Actores{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Actores</h1>
    <hr>

    <div class="row">
        <div class="col-6">
            <ul>
                {% for actor in actores %}
                    <li>{{actor}} - <a href="{% url 'actores_editar' id=actor.id %}">EDITAR</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
    </div>


</div>


{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGO POST - {% block titulo %}{% endblock %}</title>
    {% load static %}	
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">  
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    {% block estilos %}{% endblock %}
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><i class="fa fa-free-code-camp" aria-hidden="true"></i> BASE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
              </li>
  

            </ul>
            <div class="d-flex">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <span class="nav-link active text-info">Bienvenido, <b>{{request.session.usuario.nombre}}</b></span>
                </li>
              </ul>
              <a href="{% url 'index' %}" class="btn btn-outline-danger">SALIR</a>
            </div>
      </div>
    </div>

          </div>

        </div>
      </nav>


    {% block contenido %}{% endblock %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

core/templates/core/directores.html
{% extends "core/base.html"%}

{% block titulo %}Directores{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Directores</h1>
    <hr>

    <div class="row">
        <div class="col-6">
            <ul>
                {% for director in directores %}
                    <li>{{director}} - <a href="{% url 'directores_editar' id=director.id %}">EDITAR</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
    </div>


</div>


{% endblock %}

core/templates/core/index.html
{% extends "core/base.html"%}

{% block titulo %}BIENVENIDA{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Bienvenidos a Mi Aplicación</h1>
    <hr>
</div>


{% endblock %}

core/templates/core/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><i class="fa fa-free-code-camp" aria-hidden="true"></i> BASE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'directores' %}">Directores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'peliculas' %}">Peliculas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'actores' %}">Actores</a>
                </li>

          </ul>
          <div class="d-flex">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                      <span class="nav-link active text-info">Bienvenido, <b>{{request.session.usuario.nombre}}</b></span>
                  </li>
              </ul>
              <a href="{% url 'acceso:logout' %}" class="btn btn-outline-danger">SALIR</a>
          </div>
      </div>
  </div>
</nav>

core/templates/core/peliculas.html
{% extends "core/base.html"%}

{% block titulo %}Peliculas{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Peliculas</h1>
    <hr>

    <div class="row">
        <div class="col-6">
            <ul>
                {% for pelicula in peliculas %}
                    <li>{{pelicula}} - <a href="{% url 'peliculas_editar' id=pelicula.id %}">EDITAR</a></li>
                    <ul>
                        {% for actor in pelicula.actores.all %}
                            <li>{{actor}} - <a href="{% url 'actores_editar' id=actor.id %}">EDITAR</a></li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        </div>
        <div class="col-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
    </div>


</div>


{% endblock %}